### ISSUE TITLE
pretrained densenet does not work on CPU

### ISSUE THREAD

**Issue by lopuhin** [pytorch/vision#220]
When I try to initialise pretrained ``densenet121``, I get the error ``AssertionError: Torch not compiled with CUDA enabled`` (while other networks work). Using ``http://download.pytorch.org/whl/torch-0.2.0.post1-cp36-cp36m-macosx_10_7_x86_64.whl`` and ``torchvision-0.1.9`` on CPython 3.6.2 on OS X 10.12.6.

Here is the full traceback:
```
In [2]: for m in [resnet50, inception_v3, densenet121]:
   ...:     m(pretrained=True)
   ...:
venv/lib/python3.6/site-packages/torchvision/models/inception.py:65: UserWarning: src is not broadcastable to dst, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  m.weight.data.copy_(values)
Downloading: "https://download.pytorch.org/models/densenet121-241335ed.pth" to /Users/kostia/.torch/models/densenet121-241335ed.pth
100.0%
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-28619da1d19b> in <module>()
      1 for m in [resnet50, inception_v3, densenet121]:
----> 2     m(pretrained=True)
      3

venv/lib/python3.6/site-packages/torchvision/models/densenet.py in densenet121(pretrained, **kwargs)
     26                      **kwargs)
     27     if pretrained:
---> 28         model.load_state_dict(model_zoo.load_url(model_urls['densenet121']))
     29     return model
     30

venv/lib/python3.6/site-packages/torch/utils/model_zoo.py in load_url(url, model_dir, map_location)
     56         hash_prefix = HASH_REGEX.search(filename).group(1)
     57         _download_url_to_file(url, cached_file, hash_prefix)
---> 58     return torch.load(cached_file, map_location=map_location)
     59
     60

venv/lib/python3.6/site-packages/torch/serialization.py in load(f, map_location, pickle_module)
    229         f = open(f, 'rb')
    230     try:
--> 231         return _load(f, map_location, pickle_module)
    232     finally:
    233         if new_fd:

venv/lib/python3.6/site-packages/torch/serialization.py in _load(f, map_location, pickle_module)
    377     unpickler = pickle_module.Unpickler(f)
    378     unpickler.persistent_load = persistent_load
--> 379     result = unpickler.load()
    380
    381     deserialized_storage_keys = pickle_module.load(f)

venv/lib/python3.6/site-packages/torch/cuda/__init__.py in _lazy_new(cls, *args, **kwargs)
    264 @staticmethod
    265 def _lazy_new(cls, *args, **kwargs):
--> 266     _lazy_init()
    267     # We need this method only for lazy init, so we can remove it
    268     del _CudaBase.__new__

venv/lib/python3.6/site-packages/torch/cuda/__init__.py in _lazy_init()
     82         raise RuntimeError(
     83             "Cannot re-initialize CUDA in forked subprocess. " + msg)
---> 84     _check_driver()
     85     torch._C._cuda_init()
     86     torch._C._cuda_sparse_init()

venv/lib/python3.6/site-packages/torch/cuda/__init__.py in _check_driver()
     49 def _check_driver():
     50     if not hasattr(torch._C, '_cuda_isDriverSufficient'):
---> 51         raise AssertionError("Torch not compiled with CUDA enabled")
     52     if not torch._C._cuda_isDriverSufficient():
     53         if torch._C._cuda_getDriverVersion() == 0:

AssertionError: Torch not compiled with CUDA enabled
```

**Comment by alykhantejani** [comment]
I think the files we're serialized with the old method and now can't be properly read with the new serialization. I've tried loading, saving and re-loading on a CUDA enabled machine - which seems to work. 

I will try to upload these new files somewhere sensible tomorrow so that the pre-trained locations can be updated.

cc: @fmassa

**Comment by hiram94** [comment]
I have encountered the same problem. In addition, although on GPU the model using pre-trained resnet and densenet both work well and on CPU the model using pre-trained resnet works well, I am not really sure my modification, bold for GPU and italic for densenet, is correct. 

```bash
class EncoderImageFull(nn.Module):

    def __init__(self, embed_size, finetune=False, cnn_type='vgg19',
                 use_abs=False, no_imgnorm=False):
        """Load pretrained VGG19 and replace top fc layer."""
        super(EncoderImageFull, self).__init__()
        self.embed_size = embed_size
        self.no_imgnorm = no_imgnorm
        self.use_abs = use_abs

        # Load a pre-trained model
        self.cnn = self.get_cnn(cnn_type, True)

        # For efficient memory usage.
        for param in self.cnn.parameters():
            param.requires_grad = finetune

        # Replace the last fully connected layer of CNN with a new one
        if cnn_type.startswith('vgg'):
            self.fc = nn.Linear(self.cnn.classifier._modules['6'].in_features,
                                embed_size)
            self.cnn.classifier = nn.Sequential(
                *list(self.cnn.classifier.children())[:-1])
        elif cnn_type.startswith('resnet'):
            if torch.cuda.is_available():
                self.fc = nn.Linear(self.cnn.module.fc.in_features, embed_size)
                self.cnn.module.fc = nn.Sequential()
            **else:
                self.fc = nn.Linear(self.cnn.fc.in_features, embed_size)
                self.cnn.fc = nn.Sequential()**
                
        _elif cnn_type.startswith('densenet'):
            self.fc = nn.Linear(self.cnn.module.classifier.in_features, embed_size)
            self.cnn.module.classifier = nn.Sequential()_

        self.init_weights()

    def get_cnn(self, arch, pretrained):
        """Load a pretrained CNN and parallelize over GPUs
        """
        if pretrained:
            print("=> using pre-trained model '{}'".format(arch))
            model = models.__dict__[arch](pretrained=True)
        else:
            print("=> creating model '{}'".format(arch))
            model = models.__dict__[arch]()

        **if torch.cuda.is_available():**
            if arch.startswith('alexnet') or arch.startswith('vgg') or arch.startswith('densenet'):
                model.features = nn.DataParallel(model.features)
                model.cuda()
            else:
                model = nn.DataParallel(model)
                model = model.cuda()

        return model

    def init_weights(self):
        """Xavier initialization for the fully connected layer
        """
        r = np.sqrt(6.) / np.sqrt(self.fc.in_features +
                                  self.fc.out_features)
        self.fc.weight.data.uniform_(-r, r)
        self.fc.bias.data.fill_(0)

    def forward(self, images):
        """Extract image feature vectors."""
        features = self.cnn(images)

        # normalization in the image embedding space
        features = l2norm(features)

        # linear projection to the joint embedding space
        features = self.fc(features)

        # normalization in the joint embedding space
        if not self.no_imgnorm:
            features = l2norm(features)

        # take the absolute value of the embedding (used in order embeddings)
        if self.use_abs:
            features = torch.abs(features)

        return features
```

**Comment by alykhantejani** [comment]
I will re-generate the models with the new serialization today and then update the URLs in torchvision.

**Comment by soumith** [comment]
fixed in master by @alykhantejani

**Comment by hassanshallal** [comment]
Hi Folks, I am facing the same exact issue/error whenever I try to load any densenet modeL. I don't have any issue loading any other pre-trained model. I tried to download the densenet  models manually from https://github.com/pytorch/vision/pull/251/commits/489d6e7e8daf5cb992177826d78bd2ce7444646a and load them using torch.load, but I still get the error: AssertionError: (AssertionError('Torch not compiled with CUDA enabled',), <class 'torch.cuda.FloatTensor'>, ()). I am using macOS Sierra version 10.12.6.

I would really appreciate any help resolving this issue. Here is the full traceback:

`---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-43-72efa9268b42> in <module>()
----> 1 torch.load('densenet121-241335ed.pth')

/Users/hassanshallal/anaconda/lib/python2.7/site-packages/torch/serialization.pyc in load(f, map_location, pickle_module)
    229         f = open(f, 'rb')
    230     try:
--> 231         return _load(f, map_location, pickle_module)
    232     finally:
    233         if new_fd:

/Users/hassanshallal/anaconda/lib/python2.7/site-packages/torch/serialization.pyc in _load(f, map_location, pickle_module)
    377     unpickler = pickle_module.Unpickler(f)
    378     unpickler.persistent_load = persistent_load
--> 379     result = unpickler.load()
    380 
    381     deserialized_storage_keys = pickle_module.load(f)

/Users/hassanshallal/anaconda/lib/python2.7/site-packages/torch/cuda/__init__.pyc in _lazy_new(cls, *args, **kwargs)
    264 @staticmethod
    265 def _lazy_new(cls, *args, **kwargs):
--> 266     _lazy_init()
    267     # We need this method only for lazy init, so we can remove it
    268     del _CudaBase.__new__

/Users/hassanshallal/anaconda/lib/python2.7/site-packages/torch/cuda/__init__.pyc in _lazy_init()
     82         raise RuntimeError(
     83             "Cannot re-initialize CUDA in forked subprocess. " + msg)
---> 84     _check_driver()
     85     torch._C._cuda_init()
     86     torch._C._cuda_sparse_init()

/Users/hassanshallal/anaconda/lib/python2.7/site-packages/torch/cuda/__init__.pyc in _check_driver()
     49 def _check_driver():
     50     if not hasattr(torch._C, '_cuda_isDriverSufficient'):
---> 51         raise AssertionError("Torch not compiled with CUDA enabled")
     52     if not torch._C._cuda_isDriverSufficient():
     53         if torch._C._cuda_getDriverVersion() == 0:

AssertionError: (AssertionError('Torch not compiled with CUDA enabled',), <class 'torch.cuda.FloatTensor'>, ())
`

Thanks

**Comment by soumith** [comment]
@hassanshallal update your torchvision with: `pip install -U torchvision`

**Comment by hassanshallal** [comment]
Thanks a lot for the feedback, I can now upload and use the densenet pre-trained models.
