### ISSUE TITLE
Serious problem !!! C++ torchvision does not register nms in Torchscript

### ISSUE THREAD

**Issue by wvalcke** [pytorch/vision#2915]
Numerous people have reported this already, but i've nowhere seen a solution.
When loading a torch script (which works in Python) the loading fails in a C++ program.
Unknown builtin op: torchvision::nms.
Could not find any similar ops to torchvision::nms. This op may not exist or may not be currently supported in TorchScript.
Torch version is 1.6.0, Torchvision is 0.7.0.
I tried to compile the master branch of torchvision, but it does not compile anymore. The same with the 0.8.0-rc4 version.
Version 0.7.0 compiles fine. 
So i'm hoping that somebody can explain in simple terms what to do to solve this problem.

Thanks!

**Comment by vfdev-5** [comment]
@wvalcke thanks for reporting. 

> I tried to compile the master branch of torchvision, but it does not compile anymore. The same with the 0.8.0-rc4 version.

Could you please detail what you try to compile and it does not work? Which error do you have ?

In project's CI we compile every time tracing faster rcnn C++ example which work fine:
- https://github.com/pytorch/vision/tree/master/test/tracing/frcnn

**Comment by zhiqwang** [comment]
I think this problem is the same as #2736 and #2796

**Comment by wvalcke** [comment]
@vfdev-5 , thanks for your reply.
Under you see the compile error for 0.8.0-rc4 (same problem with master branch)
The used compiler : gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)


`[  3%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/image.cpp.o
In file included from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/KernelFunction_impl.h:2:0,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/KernelFunction.h:226,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/dispatch/DispatchTable.h:9,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/dispatch/OperatorEntry.h:3,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/dispatch/Dispatcher.h:3,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/runtime/operator.h:6,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/ir/ir.h:7,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/api/function_impl.h:4,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/api/method.h:5,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/api/object.h:5,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/frontend/tracer.h:9,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/autograd/generated/variable_factories.h:12,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/api/include/torch/types.h:7,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/script.h:3,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/compilemyself/vision/torchvision/csrc/cpu/image/image.h:4,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/compilemyself/vision/torchvision/csrc/cpu/image/image.cpp:2:
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h: In instantiation of ‘typename c10::guts::infer_function_traits<Functor>::type::return_type c10::impl::call_functor_with_args_from_stack_(Functor*, c10::Stack*, std::index_sequence<INDEX ...>) [with Functor = c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<void (*)(std::__cxx11::basic_string<char>, at::Tensor&), void, c10::guts::typelist::typelist<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor&> >; bool AllowDeprecatedTypes = true; long unsigned int ...ivalue_arg_indices = {0, 1}; typename c10::guts::infer_function_traits<Functor>::type::return_type = void; c10::Stack = std::vector<c10::IValue>; std::index_sequence<INDEX ...> = std::integer_sequence<long unsigned int, 0, 1>]’:
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:250:77:   required from ‘typename c10::guts::infer_function_traits<Functor>::type::return_type c10::impl::call_functor_with_args_from_stack(Functor*, c10::Stack*) [with Functor = c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<void (*)(std::__cxx11::basic_string<char>, at::Tensor&), void, c10::guts::typelist::typelist<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor&> >; bool AllowDeprecatedTypes = true; typename c10::guts::infer_function_traits<Functor>::type::return_type = void; c10::Stack = std::vector<c10::IValue>]’
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:292:79:   required from ‘c10::impl::make_boxed_from_unboxed_functor<KernelFunctor, AllowDeprecatedTypes>::call(c10::OperatorKernel*, const c10::OperatorHandle&, c10::Stack*)::<lambda()> [with KernelFunctor = c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<void (*)(std::__cxx11::basic_string<char>, at::Tensor&), void, c10::guts::typelist::typelist<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor&> >; bool AllowDeprecatedTypes = true]’
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:292:90:   required from ‘struct c10::impl::make_boxed_from_unboxed_functor<KernelFunctor, AllowDeprecatedTypes>::call(c10::OperatorKernel*, const c10::OperatorHandle&, c10::Stack*) [with KernelFunctor = c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<void (*)(std::__cxx11::basic_string<char>, at::Tensor&), void, c10::guts::typelist::typelist<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor&> >; bool AllowDeprecatedTypes = true; c10::Stack = std::vector<c10::IValue>]::<lambda()>’
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:287:38:   required from ‘static void c10::impl::make_boxed_from_unboxed_functor<KernelFunctor, AllowDeprecatedTypes>::call(c10::OperatorKernel*, const c10::OperatorHandle&, c10::Stack*) [with KernelFunctor = c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<void (*)(std::__cxx11::basic_string<char>, at::Tensor&), void, c10::guts::typelist::typelist<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor&> >; bool AllowDeprecatedTypes = true; c10::Stack = std::vector<c10::IValue>]’
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/KernelFunction_impl.h:87:9:   required from ‘static c10::KernelFunction c10::KernelFunction::makeFromUnboxedFunctor(std::unique_ptr<c10::OperatorKernel>) [with bool AllowLegacyTypes = true; KernelFunctor = c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<void (*)(std::__cxx11::basic_string<char>, at::Tensor&), void, c10::guts::typelist::typelist<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor&> >]’
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/KernelFunction_impl.h:137:114:   required from ‘static c10::KernelFunction c10::KernelFunction::makeFromUnboxedRuntimeFunction(FuncType*) [with bool AllowLegacyTypes = true; FuncType = void(std::__cxx11::basic_string<char>, at::Tensor&)]’
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/op_registration/op_registration.h:549:72:   required from ‘std::enable_if_t<(c10::guts::is_function_type<T>::value && (! std::is_same<FuncType, void(const c10::OperatorHandle&, std::vector<c10::IValue>*)>::value)), c10::RegisterOperators&&> c10::RegisterOperators::op(const string&, FuncType*, c10::RegisterOperators::Options&&) && [with FuncType = void(std::__cxx11::basic_string<char>, at::Tensor&); std::enable_if_t<(c10::guts::is_function_type<T>::value && (! std::is_same<FuncType, void(const c10::OperatorHandle&, std::vector<c10::IValue>*)>::value)), c10::RegisterOperators&&> = c10::RegisterOperators&&; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/compilemyself/vision/torchvision/csrc/cpu/image/image.cpp:21:64:   required from here
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:242:22: error: no match for call to ‘(c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<void (*)(std::__cxx11::basic_string<char>, at::Tensor&), void, c10::guts::typelist::typelist<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor&> >) (std::__cxx11::basic_string<char>, at::Tensor)’
     return (*functor)(ivalue_to_arg<std::remove_cv_t<std::remove_reference_t<guts::typelist::element_t<ivalue_arg_indices, IValueArgTypes>>>, AllowDeprecatedTypes>::call(
            ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       std::move(torch::jit::peek(*stack, ivalue_arg_indices, num_ivalue_args))
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     )...);
     ~~~~~             
In file included from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/KernelFunction_impl.h:4:0,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/KernelFunction.h:226,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/dispatch/DispatchTable.h:9,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/dispatch/OperatorEntry.h:3,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/dispatch/Dispatcher.h:3,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/runtime/operator.h:6,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/ir/ir.h:7,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/api/function_impl.h:4,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/api/method.h:5,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/api/object.h:5,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/frontend/tracer.h:9,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/autograd/generated/variable_factories.h:12,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/api/include/torch/types.h:7,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/script.h:3,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/compilemyself/vision/torchvision/csrc/cpu/image/image.h:4,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/compilemyself/vision/torchvision/csrc/cpu/image/image.cpp:2:
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/impl/WrapFunctionIntoRuntimeFunctor.h:17:22: note: candidate: decltype(auto) c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<FuncType, ReturnType, c10::guts::typelist::typelist<Tail ...> >::operator()(Parameters ...) [with FuncType = void (*)(std::__cxx11::basic_string<char>, at::Tensor&); ReturnType = void; Parameters = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor&}] <near match>
       decltype(auto) operator()(Parameters... args) {
                      ^~~~~~~~
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/impl/WrapFunctionIntoRuntimeFunctor.h:17:22: note:   conversion of argument 2 would be ill-formed:
In file included from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/KernelFunction_impl.h:2:0,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/KernelFunction.h:226,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/dispatch/DispatchTable.h:9,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/dispatch/OperatorEntry.h:3,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/dispatch/Dispatcher.h:3,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/runtime/operator.h:6,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/ir/ir.h:7,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/api/function_impl.h:4,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/api/method.h:5,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/api/object.h:5,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/jit/frontend/tracer.h:9,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/autograd/generated/variable_factories.h:12,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/csrc/api/include/torch/types.h:7,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/torch/script.h:3,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/compilemyself/vision/torchvision/csrc/cpu/image/image.h:4,
                 from /mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/compilemyself/vision/torchvision/csrc/cpu/image/image.cpp:2:
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:242:22: error: cannot bind non-const lvalue reference of type ‘at::Tensor&’ to an rvalue of type ‘at::Tensor’
     return (*functor)(ivalue_to_arg<std::remove_cv_t<std::remove_reference_t<guts::typelist::element_t<ivalue_arg_indices, IValueArgTypes>>>, AllowDeprecatedTypes>::call(
            ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       std::move(torch::jit::peek(*stack, ivalue_arg_indices, num_ivalue_args))
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     )...);
     ~~~~~             
/mnt/DataVolume/dumbo/DeepLearning/PyTorchCPP/libtorch/include/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h:244:9: error: return-statement with a value, in function returning 'void' [-fpermissive]
     )...);
         ^
CMakeFiles/torchvision.dir/build.make:257: recipe for target 'CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/image.cpp.o' failed
make[2]: *** [CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/image.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/torchvision.dir/all' failed
make[1]: *** [CMakeFiles/torchvision.d`

**Comment by wvalcke** [comment]
@zhiqwang , thanks for your reply. What has been exactly done (maybe a code sample) in the user code to get the linker to forece to link with libtorchvision.so ?
At this moment i got it working by forcing the linker to include libtorchvision.so by using the linker option --no-as-needed

`g++ -o MySoftwareBinary -Wl,--no-as-needed file1.o file2.o -lc10 -ltorch_cuda -ltorch_cpu -ltorch -ltorchvision`

But i would like to avoid this, and more finally, the software must run on Windows, so i would like to have a solution at source code level instead of compiler flags.

**Comment by fmassa** [comment]
We were supposed to have fixed it in https://github.com/pytorch/vision/pull/2798 to so that the linker doesn't prune this.

Can you double-check that you have indeed the latest master version that contains that patch?

cc @bmanga as well for thoughts

**Comment by zhiqwang** [comment]
Hi @wvalcke , sorry, I didn't have enough coding experience in the linker (and in Windows) ;(

**Comment by vfdev-5** [comment]
@wvalcke try to include `#include "torchvision/vision.h"` in your code. This should solve the issue with the linker.

**Comment by bmanga** [comment]
@wvalcke It should work in master, following @vfdev-5 's advice. I am not sure why you can't compile current torchvision though. Which version of libtorch are you using?

**Comment by wvalcke** [comment]
First of all, thank you for all your reactions, 

@bmanga : I used 1.6.0 for pytorch. As recently 1.7.0 came out i tried this version, with this version torchvision 1.8.1 compiles fine. So this problem is solved, probably the reason was using 1.6.0.
But unfortunately the problem remains with the nms not being registered in Torchscript. I have to use the linker flag to force linking with torchvision. 
@vfdev-5 : I do use  : #include <torchvision/vision.h> in 1 of my headers, but this does not force linking of torchvision. 

I tried something else:
I included : #include <torchvision/cpu/vision_cpu.h>
This leads to including Python.h, why ? But ok, i made sure it was in the include path, i did NOT add the python library in the list of link libs, that seemed fine as everything compiled & linked.
Then in some method i included the following code
`{
        torch::Tensor l_T1 = torch::zeros({4, 4});
        torch::Tensor l_T2 = torch::zeros({4});
        nms_cpu(l_T1, l_T2, 0.5);
 } `

This dummy nms method call forces the linking with torchvision, now the linker flag -Wl,--no-as-needed can be left out.
And everything works, the torchvision methods like nms are available to TorchScript.
I will try this now out under Windows 10, let's hope i get it running as good as it is now under Linux.

**Comment by bmanga** [comment]
@wvalcke I assume you built the latest release tag. I don't think the `#include <torchvision/vision.h>` solution made it into any release yet (it's only available on master), so your solution is reasonable if you are unwilling to use the master branch.

I guess this can be closed?

**Comment by wvalcke** [comment]
@bmanga: Thanks for your reply. Sorry but i thought that the new release contained that fix already. I will try again with the master branch. So yes, this issue can be closed. 
Thanks to everybody for all reactions, and many thanks to all developers making PyTorch/Torchvision available for C++ developers.

**Comment by fmassa** [comment]
@bmanga is correct, the fix from https://github.com/pytorch/vision/pull/2798 is not present in the 0.8.1 release of torchvision, so you need to compile from master for now.

**Comment by wvalcke** [comment]
@fmassa, indeed i checked the git logs and the fix is on master but not yet on 0.8.1 release. I had expectations that with the new release all reported (and fixed problems) were taken into that release.
Thanks for your replies on the topic.

P.S. I can also confirm that the 0.8.1 versions works with VS2019 under Windows 10, both using CPU & CUDA version 10.1
Keep in mind that CUDA 10.1 has a bug preventing installing the extension in VS 2019. Which will create problems when building the tochvision library with Cmake & CUDA enabled. CMake complains it cannot find CUDA.
To fix this : 
copy files under C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\extras\visual_studio_integration\MSBuildExtensions
To here (assuming Professional, modify for whatever edition you have installed):
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\BuildCustomizations

Thanks!

**Comment by fmassa** [comment]
@wvalcke do you think this is something that we should fix on torchvision side?

**Comment by wvalcke** [comment]
@fmassa : No not at all, the problem is an Nvidia one, i did not had to touch anything in torchvision sources or Cmake files. If the CUDA 10.1 extension is correctly installed, things compile out of the box under Windows (assuming jpeg, png & bzip2 is found). If not, it is clearly mentioned by cmake which variables are needed to be set, so Cmake can find the include files and libs.
