### ISSUE TITLE
Installing nightly version picks up latest release

### ISSUE THREAD

**Issue by EnricoMi** [pytorch/vision#3607]
## 🐛 Bug

I am trying to install latest torchvision nightly version but pip picks up latest release. The reason is that latest nightly packages have the same version as the latest release. You would expect the nightlies to have a higher major / minor / patch.

## To Reproduce

With `pip install --pre torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html` I would expect the latest nightly version to be installed. Pip however picks up `torchvision==0.9.0` from https://pypi.org/simple/torchvision/, which is a release version. Latest nightly package in that nightly url is `torchvision-0.9.0.dev20210324%2Bcu111-cp38-cp38-linux_x86_64.whl`, which is semantically before the release, hence it is not being picked up.

This can be worked around by adding `--no-index` to `pip`. However, I think the versioning is not correct.

## Expected behavior

I always get a nightly version.

## Environment

- OS: Linux (Ubuntu)
- Python: 3.8
- Pip: 20.0.2

**Comment by pmeier** [comment]
Can confirm this is happening. Cc @seemethere. This happens if you install `torchvision` from nightlies without including `torch` in the install command. It makes no difference if you have the torch nightly already installed. Problem vanishes if you use

```
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html
```

(note the extra `torch`)

**Comment by EnricoMi** [comment]
Including the extra `torch` does **not** fix it for me. It downloads the latest torch nightly, then picks up the torchvision release, which has the dependency of torch 1.8.0 so it then ends up installing torch 1.8.0.

**Comment by pmeier** [comment]
@EnricoMi You are right, not sure how I missed that, sorry.

**Comment by seemethere** [comment]
We believe this was an issue with our html index generation scripts for download.pytorch.org which should hopefully be resolved by https://github.com/pytorch/builder/pull/686

**Comment by EnricoMi** [comment]
When will the fix be deployed so it is worth retrying?

**Comment by EnricoMi** [comment]
Thanks for fixing!

**Comment by EnricoMi** [comment]
@seemethere The issue persists for cu110 and cu112. Is this expected as snapshots are not released for those CUDA versions?

**Comment by fmassa** [comment]
@EnricoMi I believe we are not providing binaries for c110 nor cu112, so this would be expected, but I'll let @seemethere confirm
