### ISSUE TITLE
ONNX CI workflow is broken

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5971]
Since the 5th of May our CI workflow for ONNX is broken (commit 970ba3555794d163daca0ab95240d21e3035c304). Looking at the warnings emitted by the [failing](https://app.circleci.com/pipelines/github/pytorch/vision/17339/workflows/fdf2c383-0c1e-4d52-b8e4-878948ed9763/jobs/1403424) tests

```
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
[...]
AssertionError: The values for attribute 'shape' do not match: torch.Size([1, 4]) != torch.Size([0, 4]).
```

Two models are affected `faster_rcnn` and `mask_rcnn`. To reproduce run:
```
pytest test/test_onnx.py -k "test_faster_rcnn" 
pytest test/test_onnx.py -k "test_mask_rcnn" 
```

I believe a recent patch to primtorch might be the offender here. cc @neginraoof @seemethere @mruberry

**Comment by mruberry** [comment]
It does seem like primTorch would be to blame because we also use the "prim" or "prims" prefix, but we don't have a prim::Constant or any C++ code

**Comment by pmeier** [comment]
Looking through the commit history again, pytorch/pytorch#76622 might be the offender.

**Comment by sanchitintel** [comment]
Hi @pmeier,

Could you please elaborate on how PyTorch PR #76622 could be causing this issue?

Thanks!

**Comment by pmeier** [comment]
My bad, I linked the wrong PR :facepalm: Sorry for the noise. It should have been pytorch/pytorch#76875

**Comment by pmeier** [comment]
After some painful bisection, I finally found the real offender: pytorch/pytorch#73284. After seeing that the PR title contains the phrase ONNX and our ONNX tests are failing, I have no idea how I missed that when looking at the PRs :facepalm:

**Comment by datumbox** [comment]
@BowenBao Philip confirmed above that one of the PRs submitted last week broke TorchVision and @atalman helped us revert it at https://github.com/pytorch/pytorch/pull/77349. Please review and let us know what you think.

Since the PR is 1 week old already, other PRs might depend on it. So if you believe that a separate forward fix is needed, please feel free to close the PR and issue a new fix. We just need to resolve the issues on TorchVision CI as soon as possible. Thanks in advance ashen one.

**Comment by datumbox** [comment]
Thanks. I replied at https://github.com/pytorch/pytorch/pull/73284#issuecomment-1125231189

**Comment by garymm** [comment]
I've got this failure locally with torch and torchvision built from master / head.

**Comment by BowenBao** [comment]
@datumbox @garymm We have identified the root cause. Will put out a fix PR in PyTorch shortly.

**Comment by BowenBao** [comment]
Fix has been merged in pytorch master. @datumbox please let us know if this fixes torchvision CI.

**Comment by pmeier** [comment]
We'll know when the fresh `torch` nightly drops, which is around UTC+0 10:00. I'll report back.

**Comment by pmeier** [comment]
@BowenBao With [today's nightly](https://app.circleci.com/pipelines/github/pytorch/vision/17556/workflows/651cf322-207e-4998-9d9a-51995f9cd4cf/jobs/1421697/steps?invite=true#step-102-9) the [tests are still failing](https://app.circleci.com/pipelines/github/pytorch/vision/17556/workflows/651cf322-207e-4998-9d9a-51995f9cd4cf/jobs/1421697).

**Comment by BowenBao** [comment]
Hi @pmeier, if my understanding is correct, it appears my fix has not been included in yesterday's nightly yet.

5-13 nightly https://github.com/pytorch/pytorch/commit/44bf440b53cc9641086ca9462f8cab52d7dbfaa3, head is https://github.com/pytorch/pytorch/commit/65f71c0cbeb080c13e927d37b0d23d39bac6f092, the fix commit is https://github.com/pytorch/pytorch/commit/a812c4cd96d94d51627d2af290ae87de34169ec0 after it.

**Comment by datumbox** [comment]
@atalman I wonder if you confirm the cutpoint of yesterday's nightly?

**Comment by pmeier** [comment]
Can confirm @BowenBao's assessment. YOu can verify yourself, by looking at the [`nightly` branch](https://github.com/pytorch/pytorch/commits/nightly). The cutoff for today was pytorch/pytorch@65f71c0cbeb080c13e927d37b0d23d39bac6f092. Taking that knowledge to the [`master` branch](https://github.com/pytorch/pytorch/commits/master), we can verify that pytorch/pytorch@a812c4cd96d94d51627d2af290ae87de34169ec0 was three commits late. 

It will make its way into tomorrows nightly. I'll retest and close this if the fix worked.

**Comment by datumbox** [comment]
Fixed on latest nightly
